### ISSUE TITLE
Saving user credentials generates not loadable JSON

### ISSUE THREAD

**Issue by ykelle** [omarryhan/pyfy#13]
When saving the credentials with the example 'save_user_creds.py', a JSON is generated which can not be loaded again with 'load_from_json()'. 
The function 'save_as_json()' does save the attribute 'expiry' with no value. 
(... _**expiry":,"user_id":null,**_ ...)
Therefore, loading the JSON generates following error:

> Traceback (most recent call last):
>   File "/Users/<user>/Documents/PycharmProjects/spotipy-control/venv/lib/python3.7/site-packages/pyfy/creds.py", line 129, in load_from_json
>     self.__dict__.update(json.load(infile))
> ValueError: Expected object or value

Best regards

**Comment by omarryhan** [comment]
Hi,

Thanks for reporting this bug.

Like you said, this error and the error in #13 are likely caused by trying to serialize `user_dict.expiry` as json. It isn't serializable because it's a `datetime` object. In order to be able to json serialize it, we need to first convert it to an iso datetime string and then convert it back when deserializing it. I thought it's not worth the effort and deleted it all together when being serialized. I pushed a new version a couple of minutes ago. Can you check if that fixes it for you?

Thanks.

**Comment by ykelle** [comment]
Hi,

thanks for the quick response.

Unfortunately it did not solve the problem. `getattr(out_dict, "expiry", None)` always return `None` so the attribute `expiry` never gets deleted.
I have made changes myself and created a pull request. I think this should fix the problem.
The problem only seemed to occur with ujson. Simple json used the parameter `default=str`.

Thanks and best regards

**Comment by omarryhan** [comment]
Awesome! I'll merge and update Pip with a new version now. Thank you.
